server:
  port: ${BACON_SERVER_PORT:8082}
  servlet:
    context-path: /api

spring:
  application:
    name: bacon-upms-service
  boot:
    admin:
      client:
        enabled: false

bacon:
  runtime:
    mode: micro
  remote:
    auth-base-url: ${BACON_REMOTE_AUTH_BASE_URL:http://localhost:8081/api}

management:
  endpoints:
    web:
      exposure:
        include: health,info
