spring:
  application:
    name: bacon-auth-service
  boot:
    admin:
      client:
        enabled: false

bacon:
  runtime:
    mode: micro
  remote:
    upms-base-url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
