server:
  port: ${BACON_SERVER_PORT:8085}
  servlet:
    context-path: /api

spring:
  application:
    name: bacon-payment-service

bacon:
  runtime:
    mode: micro

management:
  endpoints:
    web:
      exposure:
        include: health,info
