CREATE TABLE IF NOT EXISTS bacon_upms_sys_log (
    id BIGINT NOT NULL COMMENT '主键',
    tenant_id VARCHAR(64) DEFAULT NULL COMMENT '租户业务键',
    trace_id VARCHAR(64) NOT NULL COMMENT '链路ID',
    request_id VARCHAR(64) NOT NULL COMMENT '请求ID',
    module VARCHAR(64) NOT NULL COMMENT '业务模块',
    action VARCHAR(128) NOT NULL COMMENT '操作描述',
    event_type VARCHAR(32) NOT NULL COMMENT '事件类型',
    result VARCHAR(32) NOT NULL COMMENT '执行结果',
    operator_id BIGINT DEFAULT NULL COMMENT '操作人ID',
    operator_name VARCHAR(64) DEFAULT NULL COMMENT '操作人名称',
    client_ip VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
    request_uri VARCHAR(255) DEFAULT NULL COMMENT '请求URI',
    http_method VARCHAR(16) DEFAULT NULL COMMENT 'HTTP方法',
    controller_class_name VARCHAR(255) DEFAULT NULL COMMENT '控制器类名',
    controller_method_name VARCHAR(128) DEFAULT NULL COMMENT '控制器方法名',
    cost_ms BIGINT DEFAULT NULL COMMENT '耗时毫秒',
    error_message VARCHAR(1000) DEFAULT NULL COMMENT '异常信息',
    occurred_at DATETIME(3) NOT NULL COMMENT '发生时间',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_sys_log_tenant_id (tenant_id),
    KEY idx_sys_log_trace_id (trace_id),
    KEY idx_sys_log_occurred_at (occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统访问日志表';
