server:
  port: ${BACON_SERVER_PORT:8084}
  servlet:
    context-path: /api

spring:
  application:
    name: bacon-inventory-service

bacon:
  runtime:
    mode: micro
  inventory:
    repository:
      mode: ${BACON_INVENTORY_REPOSITORY_MODE:strict}

management:
  endpoints:
    web:
      exposure:
        include: health,info
