server {
    listen 80;
    server_name _;

    location /gateway/actuator/ {
        proxy_pass http://bacon-gateway:8080/actuator/;
    }

    location /auth/actuator/ {
        proxy_pass http://bacon-auth-service:8081/actuator/;
    }

    location /upms/actuator/ {
        proxy_pass http://bacon-upms-service:8082/actuator/;
    }

    location /order/actuator/ {
        proxy_pass http://bacon-order-service:8083/actuator/;
    }

    location /inventory/actuator/ {
        proxy_pass http://bacon-inventory-service:8084/actuator/;
    }

    location /payment/actuator/ {
        proxy_pass http://bacon-payment-service:8085/actuator/;
    }

    location /storage/actuator/ {
        proxy_pass http://bacon-storage-service:8086/actuator/;
    }
}
