spring:
  application:
    name: bacon-boot
  boot:
    admin:
      client:
        enabled: false
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false

bacon:
  runtime:
    mode: mono

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
